const translations = {
  // English translations
  "en-US": {
    "locale": "English",
    // GENERAL
    "delete-button": "Delete",
    "back-button": "Back",
    "submit-button": "Send",
    "cancel-button": "Cancel",
    "modify-button": "Modify",
    // HOME
    "home-title": "Home",
    "market-title": "Store",
    "logout-title": "Log Out",
    "account-title": "Account",
    "cart-title": "Cart",
    "login-title": "Login",
    "register-title": "Register",
    "footer-desc-website": "Loyalty Card is an online sales site that allows you to buy products but also services. You have the possibility to take advantage of our loyalty advantages by accumulating points through your purchases. In the same way, you can view your advantages by opening the 3D shop.",
    "footer-desc-project": "Loyalty Card project by : Frédéric Sananes, Kamal Hennou",
    "dashboard-title": "Dashboard",
    "3dMarket-title": "3D Store",
    // LOGIN-REGISTER
    "loginPage-title": "Identify yourself :",
    "email-input": "E-mail",
    "password-input": "Password",
    "lastname-input": "Name",
    "firstname-input": "First name",
    "phone-input": "Phone number",
    "address-input": "Address",
    "company-name-input": "Company name",
    "company-turnover-input": "Last turnover",
    "notregisted-question": "You do not have an account ?",
    "alreadyregisted-question": "Already have an account ?",
    "register-button": "Create an account",
    "form-id-title": "Your informations",
    "form-personalInfo-title": "Your personal informations",
    "form-title": "Your informations",
    "company-login-side": "Access to the company login",
    "user-login-side": "Access to the user login",
    // CART
    "cart-desc": "Your cart",
    "cart-price": "Total price : ",
    "cart-button": "Finalize the order",
    // MARKET
    "market-button": "Add to cart",
    "outofstock-button": "Sold out",
    // ACCOUNT
    "hello-title": "Hello",
    "currentorder-title": "Vos orders",
    "lastorder-title": "Your last order",
    "order-button-title": "My orders",
    "order-button-desc": "Follow, cancel, return",
    "information-button-title": "My personal information",
    "information-button-desc": "Email, password...",
    "loyaltycard-button-title": "My loyalty card",
    "loyaltycard-button-desc": "View your customer information",
    "image-title": "Image",
    "name-title": "Name",
    "date-title": "Date",
    "price-title": "Price",
    "stock-title": "Quantity",
    "balance-title": "Your balance : ",
    // COMPANY ACCOUNT
    "your-company": "Your company : ",
    "payment-access": "Access to the payment",
    "turnover-title": "Last turnover",
    "contributioncompagny-title": "You are up to date on the annual payment.",
    "notcontributioncompagny-title": "You have not yet settled your payment.",
    "lastturnover-title": "Your last declared turnover is : ",
    "danger-contribution": "You are not up to date on the payment, please proceed with the payment to access our services again.",
    // PRODUCT
    "informationproduct-title": "Product information",
    "addproduct-title": "Add item",
    "product-title": "Product",
    "service-title": "Service",
    "warehouseproduct-title": "Products in a warehouse :",
    "notwarehouseproduct-title": "Products not in a warehouse :",
    "image-title": "Image",
    "image-desc": "Choose a file",
    "name-title": "Name",
    "desc-title": "Description",
    "price-title": "Price",
    "discount-title": "Discount",
    "stock-title": "Stock",
    "type-title": "Type",
    "compagny-title": "Compagny",
    "compagny-desc": "Choose a compagny",
    // DASHBOARD
    "single-sale": "NUMBER OF UNIQUE SALES :",
    "percentage-sale": "PERCENTAGE OF LOYALTYCARD SALES :",
    "available-product": "NUMBER OF PRODUCTS AVAILABLE :",
    "stock-number": "TOTAL STOCK NUMBER :",
    "next-payment": "NUMBER OF DAYS BEFORE THE NEXT PAYMENT :",
  },

  // French translations
  "fr-FR": {
    "locale": "Français",
    // GENERAL
    "delete-button": "Supprimer",
    "back-button": "Retour",
    "submit-button": "Envoyer",
    "cancel-button": "Annuler",
    "modify-button": "Modifier",
    // HOME
    "home-title": "Accueil",
    "market-title": "Magasin",
    "logout-title": "Déconnexion",
    "account-title": "Compte",
    "cart-title": "Panier",
    "login-title": "Connexion",
    "register-title": "Inscription",
    "footer-desc-website": "Loyalty Card est un site de vente en ligne qui vous permet d'acheter des produits mais aussi des prestations. Vous avez la possibilité de profiter de nos avantages de fidélité en accumulant des points à travers vos achats. De la même manière, vous pouvez visualiser vos avantages en ouvrant la boutique 3D.",
    "footer-desc-project": "Loyalty Card, un projet par : Frédéric Sananes, Kamal Hennou",
    "dashboard-title": "Tableau de bord",
    "3dMarket-title": "Magasin 3D",
    // LOGIN-REGISTER
    "loginPage-title": "Identifiez-vous :",
    "email-input": "Adresse mail",
    "password-input": "Mot de passe",
    "lastname-input": "Nom",
    "firstname-input": "Prénom",
    "phone-input": "Numéro de téléphone",
    "address-input": "Adresse",
    "company-name-input": "Nom de l'entreprise",
    "company-turnover-input": "Dernier chiffre d'affaire",
    "notregisted-question": "Vous n'avez pas de compte ?",
    "alreadyregisted-question": "Vous avez déjà un compte ?",
    "register-button": "Créer un compte",
    "form-id-title": "Vos identifiants",
    "form-personalInfo-title": "Vos informations personnelles",
    "form-title": "Vos informations",
    "company-login-side": "Access to the company login",
    "user-login-side": "Accéder à l'espace utilisateur",
    // CART
    "cart-desc": "Votre panier",
    "cart-price": "Prix total : ",
    "cart-button": "Finaliser la commande",
    // MARKET
    "market-button": "Ajouter au panier",
    "outofstock-button": "Rupture de stock",
    // ACCOUNT
    "hello-title": "Bonjour",
    "currentorder-title": "Vos commandes",
    "lastorder-title": "Votre dernière commande",
    "order-button-title": "Mes commandes",
    "order-button-desc": "Suivre, annuler, retourner",
    "information-button-title": "Mes informations personnelles",
    "information-button-desc": "Mail, mot de passe...",
    "loyaltycard-button-title": "Ma carte de fidélité",
    "loyaltycard-button-desc": "Consulter vos informations clients",
    "image-title": "Image",
    "name-title": "Nom",
    "date-title": "Date",
    "price-title": "Prix",
    "stock-title": "Quantité",
    "balance-title": "Votre solde : ",
    // COMPANY ACCOUNT
    "your-company": "Votre entreprise",
    "payment-access": "Accéder au paiment",
    "turnover-title": "Dernier chiffre d'affaires",
    "contributioncompagny-title": "Vous êtes à jour sur le paiment annuel.",
    "notcontributioncompagny-title": "Vous n'avez pas encore réglé votre paiment de cotisation annuel.",
    "lastturnover-title": "Votre dernier chiffre d'affaires déclaré est de : ",
    "danger-contribution": "Vous n'êtes pas à jour sur le paiment de la cotisation annuel, veuillez procéder au paiment pour accéder de nouveau à nos services.",
    // PRODUCT
    "informationproduct-title": "Information du produit",
    "addproduct-title": "Ajouter un article",
    "product-title": "Produit",
    "service-title": "Prestation",
    "warehouseproduct-title": "Produits se trouvant dans un entrepôt :",
    "notwarehouseproduct-title": "Produits ne se trouvant pas dans un entrepôt :",
    "image-title": "Image",
    "image-desc": "Choisir un fichier",
    "name-title": "Nom",
    "desc-title": "Description",
    "price-title": "Prix",
    "discount-title": "Réduction",
    "stock-title": "Stock",
    "type-title": "Type",
    "compagny-title": "Entreprise",
    "compagny-desc": "Choisir une entreprise",
    // DASHBOARD
    "single-sale": "NOMBRE DE VENTES UNIQUES :",
    "percentage-sale": "POURCENTAGE DE VENTES DE LOYALTYCARD :",
    "available-product": "NOMBRE DE PRODUITS DISPONIBLES :",
    "stock-number": "NOMBRE DE STOCK TOTAL :",
    "next-payment": "NOMBRE DE JOURS AVANT LE PROCHAIN PAIEMENT :",

  },

  "es-ES":{
    "locale": "Español",
    "home-title": "Inicio"
  }
};

export {translations};
