const translations = {
  // English translations
  "en-US": {
    "locale": "English",
    // GENERAL
    "delete-button": "Delete",
    "back-button": "Back",
    "submit-button": "Send",
    // HOME
    "home-title": "Home",
    "market-title": "Store",
    "logout-title": "Log Out",
    "account-title": "Account",
    "cart-title": "Cart",
    "login-title": "Login",
    "register-title": "Register",
    "search-bar": "Looking for a product ?",
    "footer-desc-website": "Loyalty Card is an online sales site that allows you to buy products but also services. You have the possibility to take advantage of our loyalty advantages by accumulating points through your purchases. In the same way, you can view your advantages by opening the 3D shop.",
    "footer-desc-project": "Loyalty Card project by : Frédéric Sananes, Kamal Hennou",
    // LOGIN-REGISTER
    "loginPage-title": "Identify yourself :",
    "email-input": "E-mail",
    "password-input": "Password",
    "lastname-input": "Name",
    "firstname-input": "First name",
    "phone-input": "Phone number",
    "address-input": "Address",
    "connected-checkbox": "Stay connected",
    "password-forgotten-text": "Forgot your password ?",
    "notregisted-question": "You do not have an account ?",
    "alreadyregisted-question": "Already have an account ?",
    "register-button": "Create an account",
    "form-id-title": "Your informations",
    "form-personalInfo-title": "Your personal informations",
    "form-title": "Your informations",
    // CART
    "cart-desc": "Your cart",
    "cart-price": "Total price : ",
    "cart-button": "Finalize the order",
    // MARKET
    "market-button": "Add to cart",
    "outofstock-button": "Sold out",
    // ACCOUNT
    "hello-title": "Hello",
    "currentorder-title": "Vos orders",
    "lastorder-title": "Your last order",
    "order-button-title": "My orders",
    "order-button-desc": "Follow, cancel, return",
    "information-button-title": "My personal information",
    "information-button-desc": "Email, password...",
    "loyaltycard-button-title": "My loyalty card",
    "loyaltycard-button-desc": "View your customer information",
    "image-title": "Image",
    "name-title": "Name",
    "date-title": "Date",
    "price-title": "Price",
    "stock-title": "Quantity",
    // PRODUCT
    "informationproduct-title": "Product information",
    "addproduct-title": "Add item",
    "service-title": "Service",
    "warehouseproduct-title": "Products in a warehouse :",
    "notwarehouseproduct-title": "Products not in a warehouse :",
    "image-title": "Image",
    "image-desc": "Choose a file",
    "name-title": "Name",
    "desc-title": "Description",
    "price-title": "Price",
    "discount-title": "Discount",
    "stock-title": "Stock",
    "type-title": "Type",
    "compagny-title": "Compagny",
    "compagny-desc": "Choose a compagny",
  },

  // French translations
  "fr-FR": {
    "locale": "Français",
    // GENERAL
    "delete-button": "Supprimer",
    "back-button": "Retour",
    "submit-button": "Envoyer",
    // HOME
    "home-title": "Accueil",
    "market-title": "Magasin",
    "logout-title": "Déconnexion",
    "account-title": "Compte",
    "cart-title": "Panier",
    "login-title": "Connexion",
    "register-title": "Inscription",
    "search-bar": "Vous cherchez un produit ?",
    "footer-desc-website": "Loyalty Card est un site de vente en ligne qui vous permet d'acheter des produits mais aussi des prestations. Vous avez la possibilité de profiter de nos avantages de fidélité en accumulant des points à travers vos achats. De la même manière, vous pouvez visualiser vos avantages en ouvrant la boutique 3D.",
    "footer-desc-project": "Loyalty Card, un projet par : Frédéric Sananes, Kamal Hennou",
    // LOGIN-REGISTER
    "loginPage-title": "Identifiez-vous :",
    "email-input": "Adresse mail",
    "password-input": "Mot de passe",
    "lastname-input": "Nom",
    "firstname-input": "Prénom",
    "phone-input": "Numéro de téléphone",
    "address-input": "Adresse",
    "connected-checkbox": "Rester connecté",
    "password-forgotten-text": "Vous avez oublié votre mot de passe ?",
    "notregisted-question": "Vous n'avez pas de compte ?",
    "alreadyregisted-question": "Vous avez déjà un compte ?",
    "register-button": "Créer un compte",
    "form-id-title": "Vos identifiants",
    "form-personalInfo-title": "Vos informations personnelles",
    "form-title": "Vos informations",
    // cart
    "cart-desc": "Votre panier",
    "cart-price": "Prix total : ",
    "cart-button": "Finaliser la commande",
    // MARKET
    "market-button": "Ajouter au panier",
    "outofstock-button": "Rupture de stock",
    // ACCOUNT
    "hello-title": "Bonjour",
    "currentorder-title": "Vos commandes",
    "lastorder-title": "Votre dernière commande",
    "order-button-title": "Mes commandes",
    "order-button-desc": "Suivre, annuler, retourner",
    "information-button-title": "Mes informations personnelles",
    "information-button-desc": "Mail, mot de passe...",
    "loyaltycard-button-title": "Ma carte de fidélité",
    "loyaltycard-button-desc": "Consulter vos informations clients",
    "image-title": "Image",
    "name-title": "Nom",
    "date-title": "Date",
    "price-title": "Prix",
    "stock-title": "Quantité",
    // PRODUCT
    "informationproduct-title": "Information du produit",
    "addproduct-title": "Ajouter un article",
    "service-title": "Prestation",
    "warehouseproduct-title": "Produits se trouvant dans un entrepôt :",
    "notwarehouseproduct-title": "Produits ne se trouvant pas dans un entrepôt :",
    "image-title": "Image",
    "image-desc": "Choisir un fichier",
    "name-title": "Nom",
    "desc-title": "Description",
    "price-title": "Prix",
    "discount-title": "Réduction",
    "stock-title": "Stock",
    "type-title": "Type",
    "compagny-title": "Entreprise",
    "compagny-desc": "Choisir une entreprise",

  },

  "es-ES":{
    "locale": "Español",
    "home-title": "Inicio"
  }
};

export {translations};
